apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.name" . }}-env
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-30"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  {{- range $key, $value := .Values.config.env }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}
