apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "helm.name" . }}-external-secret 
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-30"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store-{{ include "helm.name" . }}
    kind: SecretStore
  target:
    name: {{ include "helm.name" . }}-secret
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.externalsecret.lockbox_id }}
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalsecret.lockbox_id }}
        property: DB_PASSWORD